#! /usr/bin/env bash

read -p "Enter to delete a bucket: " bucket_name

if [ -z "$bucket_name" ]; then
    echo "Please enter the bucket name"
    exit 1
fi

echo "$bucket_name is deleting. Please wait...!"

aws s3api delete-bucket \
--bucket $bucket_name 
